### ISSUE TITLE
Crash Report 1549544789

### ISSUE THREAD

**Issue by adamthemute** [wowsims/cata#1251]
Link:
https://wowsims.github.io/cata/rogue/subtlety/#eJzdVl1sFFUUnnNnujt72m2Hy6LTi4btWMg6CtnudsuWiLstMamgSWOMqW82KSDEENzyYoO6IFpSTCz4U4siusakoiCWJ5sYiTFZf6pL+gBYozFEY9U+KNZYTQHvnTu73e6uf4Fo4n3YzHzzne9859xzZxaX62BAEu6F7bAX4FmAEYCTAGcBpgDSBPYSOE6gHU1O6oAuTqMKy9KDqqfzvu4HNqZ0n+FhvwFSo/81zfwxaHmODGvTQ2poH6DXGDuqhUYA64zPLqjmdNBSZ/iTA4L9y1HNfIazOSCwEYE9yhUek9gcxwYB/cYkxzINFiji1jDOH9PMfUFL4xRFCmVPq5ZvzlGZkUHUmOGsF+aF9gsHs3PcwTLp4BVBOnNRDf968ZJcIAK9xquva4KtGbvnVP47+5yGaOznao8EBQGN74871wcE+S1e3CBYfp2E6ztJF7lHGwSwvySmimdB+Z8umv7PS1ujtCvfQQApHw8wSVANBW75eHx8bXhQfZc06p/niDGeI+aZHAl+lCOhL3IknP2axGcmSPKHCdJxfoK8T7RTpHqSKOfIuRq+XYtRZx7U9E/eUy0vVqG6MtorwK0CPPGO5oIRAXqYhsRcZPmQgyubVsV6MYDerfy5PusvRil6mUC/2eaGN81jJ0IFjGqMrFHoOtaGcdqChlWLNaPgo8QQxKE6NOxa3UPV3aCIUISYi5D1ijCNpCnMJJXGWBRtGqoQErCprlFpc6hOoi1O2KhB17MOvJnehFfZAU7yjYFbtqRF/5YDN4TuYCncQjfjEnsx19LHQJYrA5udQFggVWf7XSkHiOMN7PrK0REnWqOkz00bDbvNpGG2CpfT69A36ni/MOlZWMyup1Sp0eREfLWOLmX15XXlG/ImsGOALwN9EfJWnFF44+2qfE/8VnU+GxfHGgtRHwU5BeXtwS52l4OqRemasZ0my9AY3sjsvEK+0njYqcfD6yEi5c9PFuoRt5fSQDewWzHB1uI1lKF/lL/gxABp+hPZqmKf19KlRT5F76soH79isQ8PEToArB/wdrqhpLCiqqfGVWS2yXvjHyvOtnCv5uuKRFrQToVwBWusUF3pXETdE8k904fYTuyl9/+zbKU5WsJ/vmUllakDUkk/WUsfZg9eufyZv84vHjr5XTOF6S4dlUj5BsoXDm1lq7GBLqt47OPojcj7FC11uTpGM8AOAz4NjH/jyid2BW2sMLElKq2xPzp9hddMhUmu0LGyTPnT2w9sD+BO1ncZFi/XCsf1GEVW+HTQq9kSuasZkKPj2P122xTp2aXKb1cg+ZJ7dXdyQFWsLOlQfc59elNykXzSnKw/OCzWB4lWiZxKNGxy1ulEG//S8TWdiDxOth/5Cfqq7+je0hO8szu1eeOOYJfptf+l/x6de5JXUi7dky3Wuy1+6Pm2Uo7TjXTG1zYMskGfJlyOlvwdM0Nx8A==

RNG Seed: 4190340131

Wrong APL controllingAction in pop()
Stack Trace:
goroutine 13 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/cata/sim/core.runSim.func1()
	/home/runner/work/cata/cata/sim/core/sim.go:125 +0x10
panic({0x11fec0, 0x44be70})
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.(*APLRotation).popControl...

**Comment by hillerstorm** [comment]
If you save the set, click ⚙️ up to the right and select Restore Defaults and then sim again after re-selecting your race/professions etc. it should work again (does for me with the link above)
