### ISSUE TITLE
Crash Report 1925905580

### ISSUE THREAD

**Issue by robertgull** [wowsims/cata#1252]
Link:
http://localhost:3333/cata/mage/arcane/#eJzdVV1oHFUUnnNndjN70rSTm7/JbTW7EyLrmDSzs7uk3Zdsq61tqSUPIvFFzM/WKK0p2Qj+ICT+hFQQmwRMGxFpRasmxpI3A1IJiFW6WBFiqEi1tiVoMUUf2kKTeO/8hO0a2wdFwfswc+853zn3++49ZwbrVNAgDV1wAAYBDgO8B/ApwBzAPEAfgUECJwhsVQSISuyqNiYHW/a1PZPpUQOazC4BUm16UdYXwkZw4ohyfVSOvgNYpH04oUSHANdp304q+nzYkF87LEcPCcOpWVkf4YYrHPquMMxyxAAP5wgejiXajxOKfjRigBQ9Dnz5DfdfqDFEbonDz04oRpDPF0adhFS7xuFDPH7BtR0XOWeOKfog30QYhgSfn244u1Ht+yXZWl5adgcIp6J9fUPmkHMXnOA12sS4ove7wShx9+hHiqGqAauiRWlVzB+ILuMcSP/TQfv+c2kpaSs5AMOgIEFpmqyPW/G4Zdt2zI5bMfHmz1iDHW+w4jNkg7qQI9ob54i+mCPh33IkeiVHrMUBedP4RXKKwBlSfJZI58nbxToxHsfMc0ZH9/72p7K9D3b1ZLJd3fs6jVS8yeKj3vfsbsv2PtC9P/Nk726+asn0dPBp22MZIxVL3ATc010IsJuSHPA8lbACVRZERR3+FYwQFmGgIbkxmcUyzzx5Qja4EeWGhDAGGRerl3pIWyDLsYhxv3qpNc9KFUZSEt3AGGrmWjVA+UrkQ9KUdfJ+nINbeJf6A1RnlbiGIarHQKS//pDwaL98JtMEszFK78JSc52I3SUxh2HMyvqmds9kJ+t8cfRNYGOAh4C+CphhHXgPvRtDXyoeGQxNgT8VSRSHk5u3KYsJamOJUZwfEDFr+FZl06DhWvVgZXjZH+BKsbNYMsU7mWgBHvH+dwQrzDIeIf+sSEIWBt3rZK46+hWw04AzQE8Cvg5sBHA7ve8vGFabVapMQ9O+gfFsqDjXsQr5nfT+QvJlU3+m7ShS/pYit+58RQPAXgR8lj6NLWwPhumd+Qy8m8rnadJoIc8qo2J1rrch4ta3T6SJJbGems6ecl7B8OO6tYJ6ZmKE1mBoWBaMLl8lSE3NKzr1A+LWvVf+FJnbM+MDAdrIGrCWRrDkvJLP0yv3XV65J91y5x5aowJbX1jScSvrdyHdyQHbfAl+gSesuhegkW8/8gjLa4mV+rfqCkXbVrawgVIr3ZItzL/ZchpIO/kWoXEWW4kK3pSwMCrGo8SZXGyknawdd9DtWGaWesKcj0Ryozj8OrOWF1z5FClVgapPeEfB5GnFg1kOTLU9j1GJq4LpNnYvpuimQvmcB9aaEW/j6ilSKULHnGt7GfwL5DP3Re/gN5B3vy7wpSrmvmiIuV+6OW2edPbL7k8gkT7qzR5OvyJLxiTZIYecdd/edKnrKU9Xjx0R44vmza7lTHNkrzNmm7fkTotxudn+HcKtesD8l/7Z0YPpfzJdX+fnt83niv9kIb3FXV9rfhT+AF+pkoo=

RNG Seed: 4301036

Aura with 0 duration
Stack Trace:
goroutine 826 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/wowsims/cata/sim/core.runSim.func1()
	/home/runner/work/cata/cata/sim/core/sim.go:125 +0x98
panic({0x1158260?, 0x2b14aa0?})
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/panic.go:914 +0x21f
github.com/wowsims/cata/sim/c...

**Comment by hillerstorm** [comment]
If you save the set, click ⚙️ up to the right and select `Restore Defaults` and then sim again after re-selecting your race/professions etc. it should work again (does for me with the link above)

**Comment by robertgull** [comment]
Yes that works, thank you. I believe this issue occured because I exported a json from one spec, and imported it to another spec. This left the "rotation" empty and therefore crashing.
