### ISSUE TITLE
Crash Report -1794197120

### ISSUE THREAD

**Issue by Squisher123** [wowsims/cata#1276]
Link:
https://wowsims.github.io/cata/rogue/subtlety/#eJzdVl1oHFUUnnNnsjt7sptMT1Pd3CrdjLHE0ZTZmW66qT+7SV/SViGISHwzkFpbpNRNXxqqrm01IQr+m6ZaW9cX7a9ufXFRWkRYleiWCLUGFCmKqeSlNYIPFb3zs8lms/7RouBlGO589zvnO+fcc2cGWzVIw4MwArAP4E2A0wDnAKYBsgxGGOxj8DaD7rAGScHrgV7YDiTxd2m/HOh9qH/npowa0gL8FGCjNnxEiV6M6YHD48rMmIyKVjimYFg7dFyJzsR0eVZgQe39o0r05ZhgPyHYTwq2gC+LFdSmBJBr0UHCiHZJ2DwV0xWxKAlu8ayshwRr1r0EMCK4r80bh7UjjsgKT0TRLghhRXvrqHPf/Yp7v+yIPydYe2KCvsedlOnvHVP0iMrM5l7Wx+5XngUwvmVRGc+B9D8dlP3PU1srdUs/gooBsQEQZQV2q2nZpimuitFumpZZNdpN27ZMO25bcTtumnFLTD5kreqXJaZ9XWLRiRKLfVNibcXvmflFiSUvTrL0pUnWMzvJPmbKGVY/xaTz7HxYbPBSVLnQVz//SNaDWIdyuz3ogFsd8OQpxQctBwxwBVl0iR5CAbbHVyUGsQmDW8W6+kukEiUMcgf9YZtvHp/HTrbNYaRwtlaidbwLk9SBmt6A4TyEiGkOcawRNaNBDZC8GyTHFCHhI2yD5ASNLG5yj0oJbqNBbTVMmgxSFfLCHGv00A7XLK/RBt6Dd9BteI3RJEihAvhpezT7b0Xgm9AOnsEttBmXGUuFL7UAXrqe4WrXEBa4ajQivisXSOLN/Kba1pZrrRAb8mVt0y8mmXwV3kg3YCjvxv7rVGBhMo+/KHs+4q7Fd+toOW9enFe5IO8APw74BtAhKIfitsKJD+rKNYno9WU14RzDOqKaB68LFpcH+/i9LipXyK3GbkovQhN4CzfKHsqZJk03n4DIhzmSP78wl4/z+FsWaCNfjyl+O15HHCN5QLeBFPWZYl1lnNfT8oo4ndrXkWi/SmefHmA0CnwY8C7aWJVYRdbTEzJyIypqEylUqi3cq/m8LKsDjUwbruStNbKr7gvbP5EiZnqU78JBevifqVVrdJh/vmVVmcmjnif1dAM9xh+5evq5v9Z3Fl19P5i57q5uFWvxBnovHOrka7CFVtQ89kkMWt5zhqqjXJOgHPCDgC8Bfx5qdOxKaq3RsVVeOhN/dPrmXjM1OrlGxRYplU/vMPC9gLv40BWEeKWhCFxNEPK5Twddy5d5u5oDr3XccC9sm2YDr8ve1+6+9Kgs6UXWI4c8YGd6iTdpSjfvH3fGJ6lODzmTannAHWdTXZ9NOGMmZT3Nth/+CYbq7+7fMhC7pz+zedOOWF80aPxL/yi9e9NX0112oFjp787kgVe7qjluNbK5UNc4eAX6KuVzlPTvzk1fmQ==

RNG Seed: 2779499412

Aura Honor Among Thieves already registered!
Stack Trace:
goroutine 16 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/cata/sim/core.runSim.func1()
	/home/runner/work/cata/cata/sim/core/sim.go:125 +0x10
panic({0x123500, 0x3c41d90})
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.(*auraTracker).registerAura(0x3ca4498, 0x3ca4000, {...

**Comment by kayla-glick** [comment]
No longer seems to be an issue
