### ISSUE TITLE
Crash Report -171286766

### ISSUE THREAD

**Issue by Francoporto** [wowsims/cata#313]
Link:
https://wowsims.github.io/cata/hunter/beast_mastery/#eJztU01IVFEYfd93nzNvPkPvXPwZb/7MPAimKeHNmyy1xYxC5FJoY7sCExctJDfVykpEW4mBjq7SQoM2EWQxFIQRFhXjqqJNEEoihkoSRpN237zJKVpUQrvOg3fvOd+557v3/dAeAzgkoBO6oB8gCXAD4CHAa4BFgB6EfoRbCM27DGhxLUoTmpwzxpin9fTJc6fOGF6OchVI8OmvLLAWND3Tj3BthIWngLx8Y1wPjwAV83uquBw02USShSeBSnlmXLc+b265gMAzIzzmhNzPsECfClG+dRWiNOK9SpsImaAR53dUznCFqaui5lSL+XKGmR5Fc3bB7yrLSlVWc7plTVMqYrnGZBnX5OUpJazUKPerTWZ9ye9DaTpfzzB1v6juxD8q46WQcxpNsQnF0kHFzEIDLWjFNhwEiDxGGkTtP36CsP52RaPWjF1wfj9FKMxrZIWBHCysZy2sDTrZWef7GwRMAoZc/2rcghRW2rGYZcesWDQas61o1FZXreJ2rRW1Z7DEuJZGfn0BA0NpDA6nMXwljU9Qn0PvG9Te4RIGGPnJI3XCgN/0UgGx2mg3CfJKNTU+dOQ0O68tGTkt1k1VJCSnImOgLLj1HZCPKSRtmwhdYqMmjsojdFg0UHWk0gDhn4Ei4eHMRK6TbkyOgtOCoI7KI6WGLnwp8Ci9t69AqpHwQLfMcVEld5M/Umx4BBvSNbd80MqWPyVBlMkSKjR95LWdPaeKpTsIkkbW8/4qEz7pnmihfFteGsDtZP2H5NihbHlSNd4n91JQVv/SvK6BfLch1z+bO5/PnX2rL2L7Bea+u/rEeG52PHGZaeY8+rKspyPhd/WSRMXYqIOn8QZXmYuHOrJ4GW968dzBcty+icG2QEHkH/9/4YHETpb1tM/+Zt2xHeX+CdyH9mAl0eTyjfgJ+AYCJdgc

RNG Seed: 4222083147

When validating reforging for item 69880, the reforging could not be validated. 151
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/cata/cata/sim/wasm/main.go:49 +0x10
panic({0xf4400, 0x2e65200})
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.NewItem({0x110f8, 0x0, 0x0, {0x0, 0x0, 0x0}, 0x97})
	/home/runner/work/cata/cata/sim/core/database.go:353 +0x30
github.com/wowsims/cata/sim/core.NewEquipmentSet({{0xfeb6, 0x0, 0x1071, ...

**Comment by rosenrusinov** [comment]
Can't reproduce anymore and we did fix some stuff with reforging so I'm closing this as done. Please re-open if you still manage to reproduce with a new link
