### ISSUE TITLE
Crash Report 1088831064

### ISSUE THREAD

**Issue by muhnow** [wowsims/cata#448]
Link:
https://wowsims.github.io/cata/druid/balance/#eJztUU9IFFEYf9/3za6zr6TXZvBawsYhYRCE+XOxLjN68uhxu1WYdOggXqLbdIlNQVw8mHaSiDp48BC0BMtERRYkTVJZFhmR7ArBQh2KIPDNTOo5o1s/Pnjv9+f7PniPd+sgIIDzMAoVgGsAtwHuA7wBaAKECBWERYSBQwL6YBDKKraYusoqslItN0f5oQtnLp0b0wsCSh+BF0U9JtkyzMLCrLYa00ZMvE3EDbKqiTn+iGTTMPOtGVKVaG3ia41kaPAD4vpjkld2TN4uNu+SnO8ygVnToOikCk4YpqZMpuIvGySrR3fiRfFC+ZO7w2+CCr1SIyqGub1tv6j+Uts6U0Htft5IGNdEWEvo+meybgHnYvM7yW/HrCngjO8Td2qUTbho6nrOPjyklbWeOvIKsv9IUbT/tOMkG8BROJsvaRw5u4ednud6tus6juu5jjoc23Z6k3Jtz3Me4HF9NULxLkK5FqHxNkJrOUI7XMe+nx8weLiCg0sr+AS1GGkN2SdECU0cvkzZOjeY/307FYwTM99jIWXhSHAw0zuCI3OzCZ76JzIl9rtGUrz2+5efJfjiuzfQKMtczz/+eutqsJe2cHhpT31/g+yx6q2gP+M//NOwBdPWkyw=

RNG Seed: 3733043731

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/cata/sim/core.runSim.func1()
	/home/runner/work/cata/cata/sim/core/sim.go:124 +0x10
panic({0x136220, 0x1beaa60})
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.(*Dot).TickPeriod(...)
	/home/runner/work/cata/cata/sim/core/dot.go:68
github.com/wowsims/cata/sim/druid.(*Druid).applyOmenOfClarity.func7(0x38d4b60, 0x3916480, 0x38b7900, 0x38b7ac0)
	/home/runner/work/cata/cata/sim/druid/omen_of_clarity.go:85 +0x23
github.com/wowsims/cata/sim/core.(*auraTracker).OnSpellHitDealt(...)
	/home/runner/work/cata/cata/sim/core/aura.go:803
github.com/wowsims/cata/sim/core.(*Spell).dealDamageInternal(0x38b7900, 0x3916480, 0x0, 0x38b7ac0)
	/home/runner/work/cata/cata/sim/core/spell_result.go:305 +0x9a
github.com/wowsims/cata/sim/core.(*Spell).DealDamage(...)
	/home/runner/work/cata/cata/sim/core/spell_result.go:313
github.com/wowsims/cata/sim/core.(*Spell).CalcAndDealDamage(0x38b7900, 0x3916480, 0x38cc000, 0x40742a0796673518, 0x3adfb78)
	/home/runner/work/cata/cata/sim/core/spell_result....

**Comment by muhnow** [comment]
Tested around with the default pre-raid bis setup for balance and it works just fine. I swapped Power Torrent to Hurricane on the weapon enchant and I get another exception. Just throwing that in here since that setup linked in the original issue uses hurricane, this might be the culprit.
