### ISSUE TITLE
Crash Report 1438757648

### ISSUE THREAD

**Issue by Yotsutester** [wowsims/cata#476]
Link:
https://wowsims.github.io/cata/death_knight/blood/#eJztUjtoFEEY3u+fy7E3EZ07rtgcGDeLxRII7O02Mc1tUgWrNELsIsRUFmJnIGEDwsWAEmKRvRSnp6lFsBHhmvgWhSs2h4QgIj4CilpJfOTx7+0lvRE7P4ad+b/HzD/LyKM6bPgYQwCEwDdglnCH0CC8IQxlFfoxjPO4B7wCAsIAKeS0wruOJZEeOXfm4tkLOpQs/ITMqptbwvhiWunHoSiHwp6WnepBU1itYlIeVsusfzAtsbUYixn1vZYynkt7SubUDZbKHGVpgd0zkEo9bApjrttKMaHZ12Kmxq6K2WYuQXaptW3hVLd3EmA/PyWPqCqbb/dYaa55cHuPeL/Xx/Y900ytczzY2Ytz7JBaiTuO9QXIlAp/C/6WN4SU6tMv7rE77kTjmy3/aPsmrU5dOMYIRjEP9NZJzpL2Hy3knD9NDGhD2slUgaR2nwqO57me6zhFz2V4RZ6LfW6f43grdFy/2yR1NSKjGpF5JSL743ty5iPqr6ySv7hKw2FETynVIH2NtLdEBjZofJMwI5KT8n6tvTrtz4l85lSM63U/m5Dkm2lrnTKtIpjYo/N+11IlxrPSiYRplHomWmiWBl++iPG55N4ic9To6P3HL8G+7B8kFow/OVDub5D8rPpXfzCpN0tj2AV7J6Yp

RNG Seed: 0

When validating reforging for item 69878, the reforging could not be validated. 125
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/cata/cata/sim/wasm/main.go:49 +0x10
panic({0x1030c0, 0x4202e50})
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.NewItem({0x110f6, 0x0, 0x54a, {0x0, 0x0, 0x0}, 0x7d})
	/home/runner/work/cata/cata/sim/core/database.go:353 +0x30
github.com/wowsims/cata/sim/core.NewEquipmentSet({{0xfea2, 0x0, 0x106e, {0x32f0020, 0x2, 0x2}, 0x7e}, {0xeb43, 0x0, 0x0, ...}, ...})
	/home/runner/work/cata/cata/sim/core/database.go:411 +0x6
github.com/wowsims/cata/sim/core.ProtoToEquipment(0x4237f00)
	/home/runner/work/cata/cata/sim/core/database.go:418 +0xd
github.com/wowsims/cata/sim/core.NewCharacter(0x41d66c0, 0x0, 0x30b0460)
	/home/runner/work/cata/cata/sim/core/character.go:118 +0x39
github.com/wowsims/cata/sim/core.NewAgent(0x41d66c0, 0x0, 0x30b0460)
	/home/runner/work/cata/cata/sim/core/agent.go:172 +0x1e
github.com/wowsims/cata/sim/core.NewParty(0x32f2000, 0x0, 0x410c000)
	/home/runner/work/cata/cata/sim/core/raid.go:34 +...

**Comment by 1337LutZ** [comment]
@Yotsutester Closing this issue for now. We've made a lot of updates to the WowSimsExporter addon and the Sim which should solve all these problems.
Please make sure to use the addon, and not the unofficial Weakaura which hasn't been updated.
