### ISSUE TITLE
Crash Report -1834632792

### ISSUE THREAD

**Issue by Xoduzz** [wowsims/cata#534]
Link:
https://wowsims.github.io/cata/priest/shadow/#eJzFU01oE1EQ3nm727xMak1emyY+S4lB+7MlkL9t0hyabQ8iolLwEj2ZH4sUhWIueksFoS0IwZvBgx6UgkhLL4KgSC9WsVJ7KCIIUjz0UNDeChZ0920SYsG21oPfHubnzXwzb+YtdlFwgwFXYBLgAcArgI8AXwDWAUoEJgmUCcwRGPa5wQ9JM/IUZGAc5kScGcEkvkkrctPI1ezNy9dps1vlQZT2+oIuqoZ9I0pGKQNoTwlugbQrBg1bjhm7x9Ww37j/Dxb+24yUNOwaF/tqspawAk1cQULhOdGz8Xw4mcuGE9l8LBmPhvLx/nw+kUxGwtlwLBcvxPR8f64Q0gv9A4lYvJDTs3ouu0CkRaIsE9cnIq2R26pfRg8KTr8n6EAV5VCkiK1IeRMq9PFLpe5kHZyjW2uhMiMpyTpGEimKsIk7hHXx4ztPo0XuxhY61R74WQOwdt4m4tQGlmspiQ3wBIZ4H7ZrbRSYcwEs4kcfVG5WR9DRox2mCiOnJS4aiuqitHt1WxaUrqATHVHzgC4p3Basj/eybiRnTzKHcM3eYP5b4BUab9GaTT75LkhcXpElKxgDrBMPBV3onBfVn22ojebsZ6VG4+PeWkOpakORaNG8RTc/gR2MN6TsIBQM99MswXXs03rNcdEx62itTPjReeK37l4hNY+zotTUqmRBHkCf5jUTHWMWV8nHaUWparZgF3kGz7Ezv8/y/Ux9lpZfbSgstqAX0au1mv46b80tT4PYFN2cUZmTO2p3CPBObGMMnRVR4Mc2oPqWEGo3a5oMOa0/EM7/OPx1sgjfSc+EbL/5uPGwql0wpmUp+JU4hVUaNTy2f9A4Urln4U16wPYsp4+NCqymh5beWdhIR5+QQMavamXyzz/ubuiZMg6SViq83iPv/IF49wN7aC++GUO2vZW+BL8As1mzYQ==

RNG Seed: 0

runtime error: index out of range [7] with length 4
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/cata/cata/sim/wasm/main.go:49 +0x10
panic({0x1bd900, 0x305e378})
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/priest.(*Priest).applyImprovedMindBlast(0x3370000)
	/home/runner/work/cata/cata/sim/priest/talents.go:403 +0x2e
github.com/wowsims/cata/sim/priest.(*Priest).ApplyTalents(0x3370000)
	/home/runner/work/cata/cata/sim/priest/talents.go:133 +0x31
github.com/wowsims/cata/sim/priest/shadow.(*ShadowPriest).ApplyTalents(0x303bfa0)
	/home/runner/work/cata/cata/sim/priest/shadow/shadow.go:72 +0x4
github.com/wowsims/cata/sim/core.(*Character).applyAllEffects(0x3370000, {0x3ee208, 0x303bfa0}, 0x32cf680, 0x3396780, 0x326fec0)
	/home/runner/work/cata/cata/sim/core/character....

**Comment by rosenrusinov** [comment]
You have no talents selected.

**Comment by InDebt** [comment]
I don't know how the link was generated but it's actually trying to deserialize a talent tree which puts 7 points into improved mind blast talent, hence the out of range exception when trying to access the different probabilities.

Should we add some additonal backend sanity checks for talents? 😁

**Comment by kayla-glick** [comment]
Closing in favor of #1436 to better handle these errors
