### ISSUE TITLE
Crash Report 1426229762

### ISSUE THREAD

**Issue by Kacheen** [wowsims/cata#545]
Link:
https://wowsims.github.io/cata/druid/balance/#eJzjUuVgFGB0YMxgLGDsYGScwci4gpHxACPjDUbGF4yMDUyMHUyMG5gYnYQFGC0YPRgjgMo2gGWBUkIMUtdYZjGzBeQkVqYWcbAJMErlcLEI9DexAMkdW5iB5PtGEHvlcxB7NVCcXeDBemYlRgYuDoEVx5iVmBgYuEDsOVA2i8CGzyCl17tA2g5sBbFfbwaRTWDjTm5jBqpnF+jdAjJEiYOD1UA0gCWCRWstE9cPRoYRCoQMSNVhxeDEVMCYxCbFwsXExbCLydHY2MjYwMjI0NDIwMgQSBkaGBvqGhgaYAG6BkYGxsboUoeYVDiu7GcSuLWfSeL2fiaFhvtMGmf2Mxnc3M9kseUSk8PxS0wehy8xnWBivcDEfIuJ4RETkwTjC6aURmaIi4wcFkJZkQ5dzAxKZ5g4wbyGNAdBiLiIg+SsmSBw0t4SInLBXjENDK7ZO549AwJv7I0mMylESLBq0Tg1aHQ6kKK8IeU4SeopAZDA2fvewRHC/2GfwAgAyN9taw==

RNG Seed: 952677600

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/cata/sim/core.runSim.func1()
	/home/runner/work/cata/cata/sim/core/sim.go:124 +0x10
panic({0x139b40, 0x1c52c60})
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/druid.(*Druid).registerStarfireSpell.func1(0x38278c0, 0x336c800, 0x38d3900)
	/home/runner/work/cata/cata/sim/druid/starfire.go:22 +0x17
github.com/wowsims/cata/sim/core.(*Spell).applyEffects(0x38d3900, 0x38278c0, 0x336c800)
	/home/runner/work/cata/cata/sim/core/spell.go:571 +0x13
github.com/wowsims/cata/sim/core.(*Unit).RegisterSpell.(*Spell).makeCastFuncSimple.func5(0x38278c0, 0x336c800)
	/home/runner/work/cata/cata/sim/core/cast.go:236 +0x2e
github.com/wowsims/cata/sim/core.(*Spell).Cast(0x38d3900, 0x38278c0, 0x336c800)
	/home/runner/work/cata/cata/sim/core/spell.go:547 +0x1d
github.com/wowsims/cata/sim/druid.(*Druid).registerStarfireSpell.func2(0x38278c0, 0x336c800, 0x38d3b80)
	/home/runner/work/cata/cata/sim/druid/starfire.go:67 +0x22
github.com/wowsims/cata/sim/core.(*Spell).applyEffects(0x38d3b80, 0x38278c0, 0x336c800)
	/home/runner/work/cata/cata/sim/core/spell.go:571 +0x13
github.com/wowsims/cata/sim/core.(*Unit).Regis...

Export String:

{"talents":"33230221120212111031-0100000000000000000000-020331000000000000000","glyphs":{"minor":[{"spellID":57856},{"spellID":57855},{"spellID":57857}],"prime":[{"spellID":54845},{"spellID":54756},{"spellID":54829}],"major":[{"spellID":62080},{"spellID":54832},{"spellID":54828}]},"class":"druid","unit":"player","race":"NightElf","name":"Kachen","gear":{"items":[{"id":65807,"gems":[],"reforging":162},{"id":55864,"gems":[],"reforging":141},{"id":65775,"gems":[],"reforging":141},{"id":63448,"gems":[],"reforging":144},{"id":58139,"gems":[]},{"id":55264,"gems":[],"reforging":141},{"id":63439,"gems":[],"reforging":162},{"id":66941,"gems":[],"reforging":141},{"id":58140,"gems":[],"reforging":162},{"id":56408,"gems":[]},{"id":62436,"gems":[],"reforging":165},{"id":56432,"gems":[]},{"id":55787,"gems":[]},{"id":55810,"gems":[],"reforging":162},{"id":56137,"gems":[],"reforging":141},null,{"id":55821,"gems":[],"reforging":151}]},"professions":[{"name":"Herbalism","level":3},{"name":"Enchanting","level":375}],"level":85,"spec":"balance","realm":"Lakeshire"}

Thank you for your work

**Comment by Kacheen** [comment]
Crash seems to be related to Glyph of Starfire. Calculation works when removing named Glyph
