### ISSUE TITLE
Crash Report 1684609205

### ISSUE THREAD

**Issue by urnansh** [wowsims/cata#566]
Link:
https://wowsims.github.io/cata/priest/discipline/#eJzjUuVgFGB0YMxgLGDsYGScwci4gpHxACPjDUbGF4yMDUyMHUyMG5gYnYQFGC0YPRgjgMo2gGWBUkIMUvOYZzGzBeQkVqYWcbAKsEopcTEQgkocHGwGjAEsESxaa5m4fjAyjFAgZECqDisGJ6YCxkOMbFIsXEwcjIeYGE4wsVxg4r7FxPCIiUmC8QVTygemlIXMENWRDl3MDEpnmDjBvIY0B0GIuIiD5KyZIHDS3hIicsFeMQ0Mrtk7nj0DAm/sjSYzKURIsGrROH40Oh1IUd6Qcpwk9ZQASODsfe/gCOH/sE9g9OAEADKLOfc=

RNG Seed: 0

Unset unit.ReactionTime
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/cata/cata/sim/wasm/main.go:49 +0x10
panic({0x104380, 0x3e7850})
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.(*Unit).finalize(0x3190000)
	/home/runner/work/cata/cata/sim/core/unit.go:516 +0x48
github.com/wowsims/cata/sim/core.(*Character).Finalize(0x3190000)
	/home/runner/work/cata/cata/sim/core/character.go:464 +0xa
github.com/wowsims/cata/sim/core.(*Environment).finalize(0x38619e0, 0x3376280, 0x3376500, 0x32c5f80, 0x1)
	/home/runner/work/cata/cata/sim/core/environment.go:166 +0x7c
github.com/wowsims/cata/sim/core.NewEnvironment(0x3376280, 0x3376500, 0x1)
	/home/runner/work/cata/cata/sim/core/environment.go:56 +0x5
github.com/wowsims/cata/sim/core.ComputeStats(0x386a700)
	/home/runner/work/cata/cata/sim/core/api.go:20 +0x6
main.computeStats({{}, 0x0, 0x0}, {0x3852270, 0x3, 0x3})
	/home/runner/work/cata/cata/sim/wasm/main.go:68 +0x11
syscall/js.handleEvent()
	/opt/hostedtoolcache/go/1.21.10/x64/src/syscall/js/func.go:100 +0x26

**Comment by rosenrusinov** [comment]
![image](https://github.com/wowsims/cata/assets/5707996/cced26f0-b212-4377-908b-efbd4261672a)
