### ISSUE TITLE
Crash Report -99626846

### ISSUE THREAD

**Issue by Xoduzz** [wowsims/cata#567]
Link:
https://wowsims.github.io/cata/priest/shadow/#eJzlU01oVFcUfufe92benInJzTXJvF5Fn4+q4wuByWReZpJFZ3RRSmlF6Ca66vxUirQgnU27S0orUVSiLmyGFppC24CK4kYQWoobU2lEgwYRRNEsslBid1JH7b33zQxTodraZc/mnvOd73zn3PPuw002MCjAhzAJ8C3ALwA3AO4ALAOME5gkMEXgDIFtCQYO5CTzLRiDvXBG8ySDG+Ia1mhkx0fFzz74xO5glviCIGfzi9RZcb3IyWnz4Fc0eQiwi/0xY6aePH0WGmAHW3xCnWXXoyvHqUzPyZJjMnp4nCa/A6lxXab3SQ2ZbmgwdlmSZjZ4piQZyR8VsiBZS+s9c0UhRwAT7M5Tmppu9fEikht2uCaph9024FSdOpPhAKplF7slS9tGjLJ7dZ2JsttLVPWLsm8kItsgOyKLJ1yVRfZA+o/XJ/cpwmxdMb24baUSO8wxcwrAP0XwERj/U+Opf1sxamyL79VPMqLe2QJEhInEhvMkKGbKqVypmMoWy0O5THqgnBkul7O53GCqmBoqZSpDQXm4VBkIKsMj2aFMpRQUg1LxAjHmiHmFxG8S4y750nIodqPWdLq9KFpIBwaruBptEUHT/uFnswXytUIg8zttysmoodJIBquaNnGI8E3i9eez6apg2Gnv73OfNQ14n+jRPKtN5eNRg4+ILA6Ifuzze2zgsQughL+/agnZHSHAbr/LNjl52xB6oHSgW7PFOtWScS+G0bRM2POmCA/eL7bwzUjefZNHNXT6U+58Dr3aE51+h9SjR8EQdIEaiowuX4ervDjGzuru5+5b7eHpW2ZTJiF6mwONNgYaTFflLTaLjbiWi7aS5wS1wtd5nhUB9vtb5LrsPSp1d4qINWeJo+5eI00kVjObbuPknnAx4ffKwugepTWeEHbNbHjhwXeJMdzO3/nrLi/PtnapcKutsf4KQRV7/dUSb+k2YXoA9Jeyf5+1eExEm3dwxTrs4RxjNd3gcR3QukSIHQ4rQ47Cbj0QIf52+ctkDh6S5AQN33ymMNPwdhYOUMNbIjEdje8udIf4G4XXatPKfs2PhMiV/Ibd2hbzW+d/U3Y/nz5B3DHH8qfIf/5xX2TJ/YVXKRuvXHxJ3XuvpPtPLFzaTyuFrWH8KP8+/AnHcxNF

RNG Seed: 0

runtime error: index out of range [7] with length 4
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/cata/cata/sim/wasm/main.go:49 +0x10
panic({0x1bf320, 0x30704f8})
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/priest.(*Priest).applyImprovedMindBlast(0x3382000)
	/home/runner/work/cata/cata/sim/priest/talents.go:403 +0x2e
github.com/wowsims/cata/sim/priest.(*Priest).ApplyTalents(0x3382000)
	/home/runner/work/cata/cata/sim/priest/talents.go:133 +0x31
github.com/wowsims/cata/sim/priest/shadow.(*ShadowPriest).ApplyTalents(0x334a320)
	/home/runner/work/cata/cata/sim...

**Comment by rosenrusinov** [comment]
You have no talents selected

**Comment by rosenrusinov** [comment]
Duplicate of #534
