### ISSUE TITLE
Crash Report 1361830840

### ISSUE THREAD

**Issue by Mehdizaiem** [wowsims/cata#573]
Link:
https://wowsims.github.io/cata/rogue/assassination/#eJzjUuVgFGB0YMxgLGDsYGScwci4gpHxACPjDUbGF4yMDUyMHUyMG5gYnbgkgIo8GCOAyoQYpM6wzGJmC8hJrEwt4uAUYJPqZOTiEJixg1mJiYGBi11g0idmjemMQMbF7cxKjAxcLALnGlmAKiYfg6k4twUswS3w8DlYSGMyyIR3EA6Q9XU7TOXp91Ajvm1nBpI9z0Fkxw4QuWwbiDwGZveDyYNbmZW4OJgMJAOYIpgSWLTWMnH9YGQYoUDIgFQdVgxODLcYBbn4uXgFmCQYFZg0RFzPnjlju4vJ2sIk2TLV2MIgyTLZ3CA5ydAg2cgwycLIwNwi1cA4ySTF2DTRUhdIppgbJhlbpCSBuebmKWaJ5oeYGE4wsVxgYr/FxPCICWjuC6aUhcwQGyMdupgZlM4wcYJ5DWkOghBxEQfJWTNB4KS9JUTkgr1iGhhcs3cEugkI3tgbTWZSiJBg1aJxHGt0OpCivCHlOEnqKQGQwNn73sERwv9hn8AIAIgzaQ4=

RNG Seed: 2002455480

runtime error: index out of range [4] with length 4
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/cata/cata/sim/wasm/main.go:49 +0x10
panic({0x1bf320, 0x3070f30})
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/rogue.(*Rogue).registerEviscerate(0x3374000)
	/home/runner/work/cata/cata/sim/rogue/eviscerate.go:49 +0x25
github.com/wowsims/cata/sim/rogue.(*Rogue).Initialize(0x3374000)
	/home/runner/work/cata/cata/sim/rogue/rogue.go:165 +0x10
github.com/wowsims/cata/sim/rogue/assassination.(*AssassinationRogue).Initialize(0x3880d58)
	/home/runner/work/cata/cata/sim/rogue/assassination/assassination.go:31 +0x4
github.com/wowsims/cata/sim/core.(*Environment).initialize(0x39538c0, 0x39af980, 0x39afb80)
	/home/runner/work/cata/cata/sim/core/environment.go:141 +0x25
github.com/wowsims/cata/sim/core.NewEnvironment(0x39af980, 0x39afb80, 0x1)
	/home/runner/work/cata/cata/sim/core/environment.go:55 +0x4
github.com/wowsims/cata/sim/core.ComputeStats(0x31a8f00)
	/home/runner/work/cata/cata/sim/core/api.go:20 +0x6
main.computeStats({{}, 0x0, 0x0}, {0x33f54a0, 0x3, 0x3})
	/home/runner/work/cata/cata/sim/wasm/main.go:68 +0x11
syscall/js.handleEvent()
	/opt/hostedtoolcache/go/1.21.10/x...

**Comment by TheBackstabi** [comment]
Not terribly certain what to address here, as something about the setup has managed to entirely break the talents
![image](https://github.com/wowsims/cata/assets/15022529/2ab48b1d-6386-4dd9-b46e-9b62ab07f8d8)
It appears that it's attempting to read a greater value than possible on the Coup de Grace talent

**Comment by 1337LutZ** [comment]
@TheBackstabi I checked it and it looks like the URL parser is not properly parsing the talents part:
First line is the current talents string which works, second is what it's trying to import.
![image](https://github.com/wowsims/cata/assets/1216787/417241ec-117e-4b2e-a45e-a85d7b9e587b)

**Comment by kayla-glick** [comment]
Closing in favor of #1436 to better handle these errors
