### ISSUE TITLE
Crash Report -2095999561

### ISSUE THREAD

**Issue by littlejx123** [wowsims/cata#731]
Link:
https://wowsims.github.io/cata/mage/fire/#eJzlUc8rbVEUPmutfa/jPPW2G3WYnGvn1UmpSwaYnMPI0JAZ5cnAQGZvdg1eoVeXpPtjZkAGRBkoRZL8iItunvSKK7yuwasrBo9Q7+x9vD/gJiPf6Fvr+9a3VnsbX3Tg4EIfDMAwQAJgFmAd4BTgBiCKMIywiNDKpCmkVcYCKQq293d/+zqoBzhVXoHxmcc2SQTnkiyWIHsGjCJ+mSN7Wiqrh2QmqgQ9xsmOS2Uyp0iIH5+QmbVEMB//Lxr8OU8CNDnJ+cIpmWeWYN+TTLN/yKzRW2+Lt0JuURE/vYhYWPW8FHtEmu5yZJ5bQpkScuHxsrqphI+/kFA+r2J87ZA8cXtL3WnwxVsy7y2fz2fJfLLsMTk9kyWPCF0PRMrbWQermUfjAbQPilCk0IlmrRUHIAXMQENbQaqtq9vAav0ljXzJe/K/aQzfpdGOHmBk7jc2XmfQvchg214Gd5Ad4adfqF0imnCDPUPkRza4U6+s0x0lTexjsaqivW6p3y9zK1JJiV2nye8cOVW9CidOS3pf4o9TP4HhDjNQ887faY+4hdijPdsF+d8C/3FW826LXz84XfAPJVeKTQ==

RNG Seed: 0

When validating reforging for item 63498, the reforging could not be validated. 151
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.11/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/cata/cata/sim/wasm/main.go:49 +0x10
panic({0x107b00, 0x3344e40})
	/opt/hostedtoolcache/go/1.21.11/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.NewItem({0xf80a, 0x0, 0x0, {0x3806918, 0x2, 0x2}, 0x97})
	/home/runner/work/cata/cata/sim/core/database.go:362 +0x30
github.com/wowsims/cata/sim/core.NewEquipmentSet({{0xe20f, 0x0, 0x0, {0x38068f0, 0x2, 0x2}, 0xa6}, {0xf3e2, 0x0, 0x0, ...}, ...})
	/home/runner/work/cata/cata/sim/core/database.go:420 +0x6
github.com/wowsims/cata/sim/core.ProtoToEquipment(0x3112c40)
	/home/runner/work/cata/cata/sim/core/database.go:427 +0xd
github.com/wowsims/cata/sim/core.NewCharacter(0x33397a0, 0x0, 0x3118a80)
	/home/runner/work/cata/cata/sim/core/character.go:118 +0x39
github.com/wowsims/cata/sim/core.NewAgent(0x33397a0, 0x0, 0x3118a80)
	/home/runner/work/cata/cata/sim/core/agent.go:172 +0x1e
github.com/wowsims/cata/sim/core.NewParty(0x31cec60, 0x0, 0x3050a00)
	/home/runner/work/cata/cata/sim/core/raid.go:34 +0x1d
github.com/wowsims/cata/sim/core.NewRaid(0x337b780)
	/home/runner/w...

**Comment by 1337LutZ** [comment]
@littlejx123 It looks like you have an old WowSims link with a still broken reforge (in belt). Please manually change the belt to the correct randomSuffix & reforge.
