### ISSUE TITLE
Crash Report -207663349

### ISSUE THREAD

**Issue by OmegaHelix** [wowsims/cata#783]
Link:
https://wowsims.github.io/cata/warlock/affliction/#eJzjUuVgFGB0YMxgLGDsYGScwci4gpHxACPjDUbGF4yMDUyMHUyMG5gYnfgEGD0YI4CKNoDlhBikPjHPYmYLyEmsTC3iYBfgkNLkYuBiF/i1kEVjOSOQiQcqcXOwGogGsESwTGBk1DrKxPWDkWGEAiEPaplkxeDEWgCKmi4mNi4WLiYOlkNMKhyXnzIJvDjNJHH9NJPC49NMGjefMhk8Os1k8e8Sk0PTZSaPv5eYTjCxXGDivsXE8IiJSYLxBVPKB6ZpjI3MEFMtHRZCWA1hDl3MDEpnmDgh3DQHQYgKOwfJWTNB4KS9JUTkgr1iGhhcs3c8ewYE3tgbTWZSiJBg1aJxTGt0OpCivCHlOEnqKQGQwNn73sERwv9hn8AIAC6eT8s=

RNG Seed: 4255416752

When validating reforging for item 69882, the reforging could not be validated. 167
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.11/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/cata/cata/sim/wasm/main.go:49 +0x10
panic({0x107e00, 0x3349800})
	/opt/hostedtoolcache/go/1.21.11/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.NewItem({0x110fa, 0x0, 0x0, {0x0, 0x0, 0x0}, 0xa7})
	/home/runner/work/cata/cata/sim/core/database.go:362 +0x30
github.com/wowsims/cata/sim/core.NewEquipmentSet({{0x0, 0x0, 0x0, {0x0, 0x0, 0x0}, 0x0}, {0x110fa, 0x0, 0x0, ...}, ...})
	/home/runner/work/cata/cata/sim/core/database.go:420 +0x6
github.com/wowsims/cata/sim/core.ProtoToEquipment(0x320c9c0)
	/home/runner/work/cata/cata/sim/core/database.go:427 +0xd
github.com/wowsims/cata/sim/core.NewCharacter(0x3861560, 0x0, 0x39fc7e0)
	/home/runner/work/cata/cata/sim/core/character.go:118 +0x39
github.com/wowsims/cata/sim/core.NewAgent(0x3861560, 0x0, 0x39fc7e0)
	/home/runner/work/cata/cata/sim/core/agent.go:172 +0x1e
github.com/wowsims/cata/sim/core.NewParty(0x38149a0, 0x0, 0x3334910)
	/home/runner/work/cata/cata/sim/core/raid.go:34 +0x1d
github.com/wowsims/cata/sim/core.NewRaid(0x3344480)
	/home/runner/work/cata/cata/sim/core/raid.go:167 +0x1d
github.com/wowsims/cata/sim/core.(*Environment).construct(0x3861440, 0x3344480, 0x3345380)
	/home/runner/work/cata/cata/sim/core/environment.go:73 +0x8
gith...

**Comment by OmegaHelix** [comment]
Seems importing from 60u is causes the reforge issue on some shared urls. 
Here's the input with just this equipped 
[Planetary Amulet of the Flameblaze](http://wowhead.com/cata/item=69882_-114_49_36)
Mastery > Haste

```{
    "name": "Mastery Set Pre-BiS T11 Copy Copy",
    "phase": 1,
    "links": {
        "talents": "https://sixtyupgrades.com/cata/talents/warlock/1BAcDEFGHKNLOPRQS2BCAE?g=0gil1bgf2dkg"
    },
    "character": {
        "name": "test",
        "level": 85,
        "gameClass": "WARLOCK",
        "race": "ORC",
        "faction": "HORDE"
    },
    "items": [
        {
            "name": "Planetary Amulet of the Flameblaze",
            "id": 69882,
            "suffixId": -114,
            "reforge": {
                "id": 167,
                "from": 49,
                "to": 36
            },
            "slot": "NECK"
        },
        {
            "name": "Stylish Black Shirt",
            "id": 3427,
            "slot": "SHIRT"
        }
    ],
    "wishlist": [
        {
            "name": "Vicious Gladiator's Cuffs of Prowess",
            "id": 60634,
            "type": "ARMOR"
        },
        {
            "name": "Curse-Tainted Leggings",
            "id": 56218,
            "type": "ARMOR"
        },
        {
            "name": "Skardyn's Grace",
            "id": 56440,
            "type": "ARMOR"
        }
    ],
    "consumables": [],
    "buffs": [],
    "talents": [
        {
            "name": "Shadow and Flame",
            "id": 10936,
            "rank": 3,
            "spellId": 17801
        },
        {
            "name": "Bane",
            "id": 10938,
            "rank": 3,
            "spellId": 17790
        },
        {
            "name": "Improved Immolate",
            "id": 10960,
            "rank": 2,
            "spellId": 17833
        },
        {
            "name": "Dark Arts",
            "id": 10992,
            "rank": 3,
            "spellId": 85284
        },
        {
            "name": "Demonic Embrace",
            "id": 10994,
            "rank": 3,
            "spellId": 18699
        },
        {
            "name": "Master Summoner",
            "id": 11014,
            "rank": 2,
            "spellId": 18710
        },
        {
            "name": "Mana Feed",
            "id": 11020,
            "rank": 2,
            "spellId": 85175
        },
        {
            "name": "Molten Core",
            "id": 11024,
            "rank": 3,
            "spellId": 47247
        },
        {
            "name": "Decimation",
            "id": 11034,
            "rank": 2,
            "spellId": 63158
        },
        {
            "name": "Demonic Pact",
            "id": 11042,
            "rank": 1,
            "spellId": 47236
        },
        {
            "name": "Metamorphosis",
            "id": 11044,
            "rank": 1,
            "spellId": 59672
        },
        {
            "name": "Emberstorm",
            "id": 11181,
            "rank": 2,
            "spellId": 17955
        },
        {
            "name": "Ancient Grimoire",
            "id": 11188,
            "rank": 2,
            "spellId": 85110
        },
        {
            "name": "Inferno",
            "id": 11189,
            "rank": 1,
            "spellId": 85105
        },
        {
            "name": "Demonic Aegis",
            "id": 11190,
            "rank": 2,
            "spellId": 30144
        },
        {
            "name": "Impending Doom",
            "id": 11198,
            "rank": 3,
            "spellId": 85108
        },
        {
            "name": "Cremation",
            "id": 11199,
            "rank": 2,
            "spellId": 85104
        },
        {
            "name": "Hand of Gul'dan",
            "id": 11201,
            "rank": 1,
            "spellId": 71521
        },
        {
            "name": "Fel Synergy",
            "id": 11206,
            "rank": 1,
            "spellId": 47230
        },
        {
            "name": "Demonic Rebirth",
            "id": 11713,
            "rank": 2,
            "spellId": 88447
        }
    ],
    "glyphs": [
        {
            "name": "Glyph of Life Tap",
            "id": 45785,
            "type": "MAJOR"
        },
        {
            "name": "Glyph of Shadow Bolt",
            "id": 42467,
            "type": "MAJOR"
        },
        {
            "name": "Glyph of Soul Swap",
            "id": 42466,
            "type": "MAJOR"
        },
        {
            "name": "Glyph of Drain Soul",
            "id": 43390,
            "type": "MINOR"
        },
        {
            "name": "Glyph of Unending Breath",
            "id": 43389,
            "type": "MINOR"
        },
        {
            "name": "Glyph of Ritual of Souls",
            "id": 43394,
            "type": "MINOR"
        },
        {
            "name": "Glyph of Corruption",
            "id": 42455,
            "type": "PRIME"
        },
        {
            "name": "Glyph of Metamorphosis",
            "id": 45780,
            "type": "PRIME"
        },
        {
            "name": "Glyph of Immolate",
            "id": 42464,
            "type": "PRIME"
        }
    ],
    "points": [
        {
            "name": "Demonology",
            "stats": {
                "spellDamage": 1,
                "intellect": 1,
                "critRating": 0.6,
                "hasteRating": 0.7,
                "hitRating": 1.7,
                "masteryRating": 1,
                "metaSockets": 100,
                "redSockets": 19,
                "yellowSockets": 19,
                "blueSockets": 19,
                "prismaticSockets": 19
            }
        }
    ],
    "stats": {
        "agility": 68,
        "arcaneDamage": 401,
        "armor": 136,
        "attackPower": 226,
        "crit": 2.97,
        "dodge": 2.71,
        "fireDamage": 401,
        "frostDamage": 401,
        "haste": 0.45,
        "hasteRating": 57,
        "health": 44350,
        "hit": 1.19,
        "hitRating": 143,
        "holyDamage": 401,
        "intellect": 411,
        "mana": 26438,
        "masteryRating": 86,
        "natureDamage": 401,
        "parry": 5,
        "shadowDamage": 401,
        "spellCrit": 2.33,
        "spellDamage": 401,
        "spellHaste": 0.45,
        "spellHit": 1.4,
        "spirit": 183,
        "stamina": 459,
        "strength": 66
    },
    "exportOptions": {
        "buffs": true,
        "talents": true
    }
}```

**Comment by 1337LutZ** [comment]
@OmegaHelix For now we actually remove the random suffixes (including the reforge) from an item because 60U doesn't export them properly. This can result in a random suffix that has the correct stat names, but wrong stat values.
I created another ticket to improve on this which will allow us to actually add and handle the faulty 60U suffixes properly.
