### ISSUE TITLE
Crash Report -706906230

### ISSUE THREAD

**Issue by alperhankendi** [wowsims/cata#848]
Link:
https://wowsims.github.io/cata/mage/fire/#eJzlUktoE2EQ3pl/m6Zbob+hytqD+bsgxEJls1FQL9nUSzyoRQXrcWm27eI2ie1KsXhIq4fQk4rSpicLWjwoKB7EiiBaX9hI7MHXpSIRcxBaH6ilqXUfEQS9FPUgfnuZ+ef7vhlmVljnBwoqdEEasgAjAOcBbgI8AygBZBCyCJcQWniHFOAa5qpGia/V1A7rPf4aSho+ghCgE4tEnGWS70KOnx8moXMgVNPCGzeoozfsYolJZNaujIAg0OwYL2ZYaNhRLiwQcSYo+eaGiaMcd+pXnhBxPigBJ1D61I6LQYm3xZxnN1Qmks9OHTvX4rrtf5y5FpUWdfRimYjloNfTVq2gJxaJl407s03ddbXVdKbo1nn6uEyEVfTsKV7+9HXJA4gDzBvo9iQRF4KOczUtXXU8JL+/Sl7byrfxTXdQ+ALcf4pA/E85beVaMA2jwAsocBMYleWI/BOalYgciciKEg4rclixv4gSCTf/gnoLmf9DHunnPIpLeWTv8xh6l0d58BFuLk6j+nAa7yNfwNoXyL1CFKGEiQHijbJRHatE+9UhwkmnfTVululQV3rv9eqa0ZyDB9Et3ksh2tjh4kk0lp9y8DaqnCHp4iT21+7QOru1PhaWWZy1idD0l/+X1mPqcuiZxL1l8UOXB2PL4f8Id1uZXRjLgbfA59GKF6+ehIN+CNRv705rps5261q7ZaSSbK/RrTftjKf6mJlKdrI+wzSZ1WUTNCPBLO2AzqwUq4jiupZgRpLt0dtTyUTvBhaKdVh6j8s3koZlaKZ9hd71jV7PelW5hunsIOlf3WJq/YZtvy2V7LV6DrVb3rX2/fPXKhzd9HvX4o68VnOVFbz8fi1OleEbwZHnJA==

RNG Seed: 305688748

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 36 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.12/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/cata/sim/core.runSim.func1()
	/home/runner/work/cata/cata/sim/core/sim.go:124 +0x10
panic({0x140160, 0x1d08020})
	/opt/hostedtoolcache/go/1.21.12/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.(*Dot).periodicTick(0x3387110, 0x38ddd40)
	/home/runner/work/cata/cata/sim/core/dot.go:224 +0x26
github.com/wowsims/cata/sim/core.(*Simulation).Step(0x38ddd40)
	/home/runner/work/cata/cata/sim/core/sim.go:526 +0x25
github.com/wowsims/cata/sim/core.(*Simulation).runPendingActions(...)
	/home/runner/work/cata/cata/sim/core/sim.go:483
github.com/wowsims/cata/sim/core.(*Simulation).runOnce(0x38ddd40)
	/home/runner/work/cata/cata/sim/core/sim.go:370 +0x7
github.com/wowsims/cata/sim/core.(*Simulation).run(0x38ddd40)
	/home/runner/work/cata/cata/sim/core/sim.go:338 +0x3f
github.com/wows...

**Comment by kayla-glick** [comment]
Appears to be fixed
