### ISSUE TITLE
Crash Report -1316937867

### ISSUE THREAD

**Issue by mykolasmiro** [wowsims/cata#865]
Link:
https://wowsims.github.io/cata/warlock/demonology/#eJzlVV1oHFUUnnPvnd2ZE2omN3+TW3G3o8I6NOnMrmloat1NBYm+WF8kKIKVWKUoLYl98C1R0NgWiUZsMqDQgqhYSkkf/MMfQmMjSWHTaK1GiQaTrLSyoigtreKdv+2m6kNRnzwve+53vvOde849u4s3amBAAR6B3TAEMArwOsBHAGcASgADBIYIHCWw9RoDuqFHko4GMa6IuTUeTWx7dPsTD/VpqqGJZUBuvFOkZjlt6YfH2OdFulSkyIyTxynWGitlapbSFi0foJm9IIH39jNzJAIO+Lnzp6m5kLISErggsRHANcYxiV1IWaBkngc0jDPy+HXKYpKiZIZ9lZU3qJXYNxrLcuPFS9R8Lh2olEOVWuOXKWpeSoWlpE7SGLpIM6/6zszHAYUZC99ReXy6RDP7AdE4Ifv4OeWXQMNbpubFVOY1n1Z6i1o1muo0bmM9bBjAniR4HpT/qfHuf0upU9mq7vYX6wWSQIZEo++STsfJOautNZdzs9IknnOdrPRdt9XJZZ3sat4EuVb7ZpoYny4R87Npkl6eJpkvlkhhcI50PzlHpggrkpovibJIykmTYgNqQpbVJs6CpaH0Wl2nHxsj9PsFZumYRLX15rYqeGJyFdyASaEi1abUarQeE0K2Y9ZFYLat/bLC6Cn6V7BXgiqYM0E6FX6/uA/b+HrUx8HnDB5nsXtouuK+MqvG7lNvq/wm1Ht37Xrs4T3b+3p5qH3wGRJ5vw+qkXduGPjd4i4kXOF3oPrgnr7+x3mldV7plocNHovz5PUjaD6OfUUi5zBwV2zAG7iFuEiSkSrqHkSysStF7DjMG0V9fH+J+0WMs5OUbxGbMcsdrLfrNMbJvYoIxrOxQ740ttjNEsSfKkWEdJDKBwwucqSG3yI60eFtATPxZ+ZGtx/r7FpN5XLOESST4xn5xV2+AYVtXpEdbIqb/ft0f9i3iS7s4O241m654pq6R6Kdwya7QQb1UzHg3xzBjXeSd4h2XG/bGuX6Tpkvx5wGsXacmBpwzSPh5AV6rBKMHsMSaWy2G2Vicmf4LELzWORF7xQM/VAw9G+PMBF98mYNLr/G7AdqEFiR+1DFH/uViOiTd4vbcQvfvKrcPIvLzTNM29f5Q7pTEU3jpF5yKqGw3Wy8SijC/Xp5H63eiN/eZPHXg18v1qHJm+LQhz9Q1BdZzPJ1Zt2Kjp+gi2S0DiXS+yN5CQZp+MOzqXAw9AbuKeylijVD9PC4o1AXMm4ttHhjvn2S3xQixfy6HYGdznednPHtXD47QtI9pmr/x38GmWcLV0Mf6D1xVfx/YuFw3i8XusLz+fwD8AdZF0Jj

RNG Seed: 455419891

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 23 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.12/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/cata/sim/core.runSim.func1()
	/home/runner/work/cata/cata/sim/core/sim.go:125 +0x10
panic({0x141220, 0x1d2a800})
	/opt/hostedtoolcache/go/1.21.12/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.(*Timer).ReadyAt(...)
	/home/runner/work/cata/cata/sim/core/cooldown.go:37
github.com/wowsims/cata/sim/warlock.(*Warlock...

**Comment by mykolasmiro** [comment]
in rotation tab selected succubus for the demon lock as a pet

**Comment by mykolasmiro** [comment]
<img width="789" alt="image" src="https://github.com/user-attachments/assets/2f5dcefd-f599-4045-a903-334799838b3b">
