### ISSUE TITLE
Crash Report 956529866

### ISSUE THREAD

**Issue by Alleboom** [wowsims/cata#957]
Link:
http://localhost:3333/cata/death_knight/unholy/#eJzjkuBgdGBMYGxgZJzByPiBkbGDiXEDE+MFJkYnTgGgTAHjBEZGIQapVrZZzGwBOYmVqUUcjAJcUg8YuYQEtl5nlninoMR2bAZz+wxmjXmMXGwCi/8wa9Rw8Quc6GGReKagBJZoZOTiFFj/nFniB5dGLVDfsj/MEvflldj+TofpExDoO8Is0SqnxAIUYNBYzsjFKzDnL7MSyyQQdykjF5/Avj/MSmxAWaAI0AIhgXl/mSXmK4CFQIYAtQgKHL3GLNGhADYYooxd4OQxZpB+NoF1YIexCNz7wwwS3sGsMZ2Ri0vgJ9AtK6Q0JjJyMXDxCCx+xqzE/G46s0YXoxI3B6OBRABjBCgEtB4wSTBz3WBkGKZAqGHAvWbF4MQQxS/Fy8UpCBH4YC/EsIvJzsjA2AAd6BpiCIEEjYEqjY0MjYwNjI0NDUEMw0NMKhzzrzAJzL3CJPHmKZNC7xUmjU3XmAzmXGGy6L/C5DD5CpPHjKtMJ0BJnuUWE8MjJiYJxhdMKY3MEEeIOCyEsiIdupgZlI4zeTBzgvkNaQ6CMDWSs2aCwEl7S4jIBXvFNDC4Zu949gwIvLE36mEqWPWZsYo7KDEzRSEksSg9tUQhQoJVi06pSqPTgZrGNaQcRzbPx2LuHEd0NeDQaFjE6TiTERJAN+2halgcANaun38=

RNG Seed: 2860483917

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 191 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/wowsims/cata/sim/core.runSim.func1()
	/home/runner/work/cata/cata/sim/core/sim.go:125 +0x98
panic({0x1ab4be0?, 0x3ff1d30?})
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/panic.go:914 +0x21f
github.com/wowsims/cata/sim/core.(*Simulation).advanceTasks(0xc0069830e0)
	/home/runner/work/cata/cata/sim/core/sim.go:546 +0x69
github.com/wowsims/cata/sim/core.(*Simulation).Step(0xc0069830e0?)
	/home/runner/work/cata/cata/sim/core/sim.go:503 +0xd2
github.com/wowsims/cata/sim/core.(*Simulation).runPendingActions(...)
	/home/runner/work/cata/cata/sim/core/sim.go:481
github.com/wowsims/cata/sim/core.(*Simulation).runOnce(0xc0069830e0?)
	/home/runner/work/cata/cata/sim/core/sim.go:368 +0x30
github.com/wowsims/cata/sim/core.(*Simulation).run(0xc0069830e0)
	/home/runner/work/cata/cata/sim/core/sim.go:335 +0x2db
github.com/wowsims/cata/sim/core.runSim(0xc005ff3e00, 0xc0000b6a80, 0x0, {{0xc001e4e8f8?}})
	/home/runner/work/cata/cata/sim/core/sim.go:180 +0x2c7
github.com/wowsims/cata/sim/core.(*...

**Comment by InDebt** [comment]
Cheers!

We've recently updated how stats are handled internaly. Is it possibel that you opened your browser with a saved instance? This might lead to inconsistencies. Usually this should be removed by simply refreshing the page.

Make sure you're running the latest version of the local sim.

Does the error persist?

**Comment by 1337LutZ** [comment]
Closed due to no reaction for 4 weeks
